/** Adapted from the CNI website content supplied by the user. */
export type Division = { title:string; kicker:string; location:string; description:string; image:string; fallback:string; alt:string; href:string; };
export const divisions:Division[] = [
 {title:'Automotive Division',kicker:'Premium mobility',location:'Riyadh · Saudi Arabia',description:'TGA-licensed premium rental fleet, luxury VIP transport and commercial car hire.',image:'https://crescentnovainternational.com/divisions/automotive.webp',fallback:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200',alt:'Premium automotive and transport',href:'https://crescentnovainternational.com/divisions#automotive'},
 {title:'Business Facilitation Centre',kicker:'Market entry',location:'Kingdom of Saudi Arabia',description:'Support for company setup, licensing, corporate banking, office leasing and joint-venture structuring.',image:'https://crescentnovainternational.com/divisions/business-facilitation.webp',fallback:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200',alt:'Contemporary commercial architecture',href:'https://crescentnovainternational.com/divisions#business-facilitation'},
 {title:'Tour & Travel',kicker:'Journey & concierge',location:'Makkah · Madinah',description:'Umrah packages, corporate delegations, premium travel and concierge services.',image:'https://crescentnovainternational.com/divisions/tour-travel.webp',fallback:'https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=1200',alt:'Architecture and travel',href:'https://crescentnovainternational.com/divisions#tour-travel'},
 {title:'Real Estate & Advisory',kicker:'Property & advisory',location:'Riyadh · Jeddah',description:'Access to commercial, residential and industrial assets informed by feasibility research.',image:'https://crescentnovainternational.com/divisions/real-estate.webp',fallback:'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200',alt:'Contemporary residential architecture',href:'https://crescentnovainternational.com/divisions#real-estate'},
 {title:'Home Services — Mundus',kicker:'Connected home care',location:'Kingdom of Saudi Arabia',description:'Residential maintenance, MEP, cleaning and subscription-based care for corporate compounds.',image:'https://crescentnovainternational.com/divisions/mundus.webp',fallback:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200',alt:'Contemporary residential interior',href:'https://crescentnovainternational.com/divisions#mundus'},
 {title:'Hospitality Management',kicker:'Executive accommodation',location:'Riyadh · Saudi Arabia',description:'Boutique hotel management, serviced apartments and corporate accommodation.',image:'https://crescentnovainternational.com/divisions/hospitality.webp',fallback:'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200',alt:'Hospitality and hotel architecture',href:'https://crescentnovainternational.com/divisions#hospitality'},
 {title:'Logistics — My Truck',kicker:'Connected freight',location:'Dammam · Riyadh · Jeddah',description:'Shared-load freight matching between the Kingdom’s major logistics hubs.',image:'https://crescentnovainternational.com/divisions/my-truck.webp',fallback:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200',alt:'Freight logistics warehouse',href:'https://crescentnovainternational.com/divisions#my-truck'},
 {title:'CNI AI & Digital Division',kicker:'Digital growth',location:'Kingdom of Saudi Arabia',description:'AI automation, CRM and sales systems, enterprise software, creative marketing, cloud, data and cybersecurity.',image:'https://crescentnovainternational.com/divisions/ai-and-digital.webp',fallback:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1200',alt:'Modern digital workspace',href:'https://crescentnovainternational.com/divisions#ai-digital'}
];
export const topics = {
 business:{number:'02 / 08',title:'Business Facilitation Centre',text:'KSA market entry support for licensing, company registration, corporate banking, office leasing and JV structuring.',href:'https://crescentnovainternational.com/divisions#business-facilitation'},
 mobility:{number:'01 / 08',title:'Automotive Division',text:'Premium rental fleets, VIP transport and commercial car hire across Saudi Arabia.',href:'https://crescentnovainternational.com/divisions#automotive'},
 realestate:{number:'04 / 08',title:'Real Estate & Advisory',text:'Commercial, residential and industrial opportunities in Riyadh and Jeddah, informed by feasibility intelligence.',href:'https://crescentnovainternational.com/divisions#real-estate'},
 digital:{number:'08 / 08',title:'CNI AI & Digital Division',text:'Enterprise software, intelligent automation, CRM and digital growth services.',href:'https://crescentnovainternational.com/divisions#ai-digital'},
 hospitality:{number:'06 / 08',title:'Hospitality & Travel',text:'Serviced apartments, hotel management, travel coordination, Umrah packages and corporate delegations.',href:'https://crescentnovainternational.com/divisions#hospitality'}
} as const;
export type TopicKey = keyof typeof topics;
